columns:
  - field: productline
    showdetails: true 
  - field: textdescription
    coltitle: description

rowkey: productline

tools: 
  - actionid: SHOW

js: jslogic

click:
   - field: productline
     jsaction: JS.clickproductlineproducts
