columns:
  - field: productcode
  - field: productname
    props:
      width: 180
  - field: productscale
  - field: productvendor
    props:
      width: 180
  - field: quantityinstock
    props:
      type: number
  - field: buyprice
    props:
      type: number
  - field: msrp
    props:
      type: number

tools: 
  - actionid: SHOW


jstitle: JS.productlineproductstitle
