columns:
  - field: productcode    
    showdetails: true 
  - field: productname
  - field: productline
  - field: productscale
  - field: productvendor
  - field: quantityinstock
    fieldtype: number
  - field: buyprice
    fieldtype: number
  - field: msrp
    fieldtype: number

rowkey: productcode