columns:
  - field: productline
    showdetails: true 
  - field: textdescription
    coltitle: description
  - field: actions
    actions:
       actions:
       - message: products
         jsclick: JS.productlineaction
       
rowkey: productline

js: jslogic
