fields:
  - field: productcode
  - field: productname
  - field: productscale
  - field: productvendor
  - field: quantityinstock
    type: number
  - field: buyprice
    type: number
  - field: msrp
    fieldname: msrp
    type: number

allreadonly: true
