fields:
  - field: productcode
  - field: productname
  - field: productscale
  - field: productvendor
  - field: quantityinstock
    props:
      type: number
  - field: buyprice
    props:
      type: number
  - field: msrp
    fieldname: msrp
    props:
      type: number

allreadonly: true
